"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Bell, Braces, Cloud, Code2, CreditCard, Database, GitBranch, Globe2, Layers3, LockKeyhole, MessageSquare, Monitor, Server, ShieldCheck, Video } from "lucide-react";
import styles from "./architecture.module.css";

const layers = [
  { id: "frontend", icon: Monitor, title: "Frontend experience", technology: "Next.js · React · TypeScript", detail: "Implemented with the Next.js App Router, React, TypeScript and Tailwind CSS. Server-rendered route shells and focused interactive components share accessible UI primitives and responsive design tokens.", status: "Implemented frontend" },
  { id: "backend", icon: Server, title: "Service architecture", technology: "Node.js · REST APIs", detail: "Proposed: NestJS or Next.js API routes expose typed authentication, booking, availability and session services. In this prototype those contracts use a local mock adapter, with no backend dependency.", status: "Proposed backend" },
  { id: "database", icon: Database, title: "Database & consistency", technology: "PostgreSQL · AWS RDS", detail: "Proposed: PostgreSQL relational records and transactional slot reservations prevent double bookings across clients. This prototype uses versioned browser storage and checks intervals locally; it is not a distributed reservation system.", status: "Proposed database" },
  { id: "auth", icon: LockKeyhole, title: "Identity & access", technology: "OAuth · Secure sessions", detail: "Proposed: OAuth/JWT where appropriate, protected server sessions, role-based permissions and server-enforced record ownership. The prototype's role switching is navigation simulation, not secure authentication.", status: "Proposed authentication" },
  { id: "cloud", icon: Cloud, title: "Cloud infrastructure", technology: "AWS · CloudFront · S3", detail: "Proposed: CloudFront delivers static assets from S3, ECS or Lambda hosts services, RDS manages PostgreSQL and CloudWatch supports observability. No AWS resources are deployed by this prototype.", status: "Proposed infrastructure" },
  { id: "video", icon: Video, title: "Video infrastructure", technology: "VideoService adapter", detail: "Proposed: Daily, Agora or Twilio provides tokenized consultation rooms behind a VideoService adapter. No real camera or microphone access occurs in this prototype; participants and device controls are clearly simulated.", status: "Simulated now · Provider undecided" },
  { id: "chat", icon: MessageSquare, title: "Real-time conversations", technology: "WebSockets · Socket.IO", detail: "Proposed: authenticated room-scoped WebSockets or Socket.IO provide delivery acknowledgements and message history. This prototype stores messages locally with deterministic scripted replies and simulated read receipts.", status: "Simulated now · Proposed transport" },
  { id: "notifications", icon: Bell, title: "Thoughtful reminders", technology: "Email · SMS · Push", detail: "Proposed: background notifications deliver booking confirmations and reminders with consent, retry and delivery tracking. This prototype provides in-app confirmation and a downloadable calendar event; it sends no email, SMS or push.", status: "Proposed notifications" },
  { id: "payments", icon: CreditCard, title: "Payment experience", technology: "Razorpay / Stripe", detail: "Proposed: a payment provider handles checkout, verified webhooks, refunds and settlement. The prototype's payment result is simulated. It collects no payment details and never transfers money.", status: "Simulated now · Provider undecided" },
  { id: "deployment", icon: GitBranch, title: "Shipping with confidence", technology: "Docker · CI/CD · AWS", detail: "Proposed: a containerized build, CI type checks and tests, controlled releases and monitoring. The local prototype includes production-build, unit and browser-test commands but has not been deployed to cloud infrastructure.", status: "Local checks · Proposed deployment" },
];
const pipeline = [
  { title: "Client", caption: "Responsive web experience", icon: Globe2 },
  { title: "Next.js frontend", caption: "React · TypeScript · Tailwind", icon: Monitor },
  { title: "API layer", caption: "Typed REST contracts", icon: Braces },
  { title: "Authentication", caption: "Roles · Secure sessions", icon: LockKeyhole },
  { title: "Booking service", caption: "Reservations · Payment state", icon: Layers3 },
  { title: "Availability service", caption: "Schedules · Conflict checks", icon: CalendarIcon },
  { title: "Session service", caption: "Room lifecycle · Feedback", icon: Video },
  { title: "PostgreSQL", caption: "Consistent system of record", icon: Database },
];
function CalendarIcon({ size = 22 }: { size?: number }) { return <Layers3 size={size} />; }

export function Architecture() {
  const [selected, setSelected] = useState(layers[0]);
  return <div className={styles.architecture}>
    <section className={styles.hero}><div className="container"><div className={styles.heroIcon}><Code2 size={30} strokeWidth={1.1} /></div><h1>Built for scale, security<br />& real-time experiences.</h1><p>A thoughtful experience on the outside.<br />An intentional architecture underneath.</p><a href="#architecture" className="btn btn-gold">Explore the architecture <ArrowDown size={16} /></a></div></section>
    <section className="container home-section"><div className={styles.current}><div><span className={styles.status}><span />Implemented prototype</span><h2>Real interactions.<br />An honest foundation.</h2></div><div><p>What you can use today is a complete frontend demonstration: responsive screens, a connected booking journey and a locally simulated consultation experience.</p><div className={styles.chips}>{["Next.js App Router", "React + TypeScript", "Tailwind CSS", "Typed mock services", "Browser storage"].map(item => <span key={item}>{item}</span>)}</div><p className={styles.fine}>No live backend, payment gateway, video provider or cloud infrastructure is connected. Your demo data stays in this browser.</p></div></div></section>
    <section className={styles.diagramSection} id="architecture"><div className="container"><div className="center-heading"><h2>Designed to grow, without growing apart.</h2><p>Clear boundaries. Connected services. One consistent experience.</p><span className={styles.proposed}>Proposed production architecture</span></div><div className={styles.cloudBoundary}><div className={styles.cloudLabel}><Cloud size={21} /><span>AWS infrastructure</span><span>Proposed</span></div><div className={styles.diagram}><ol className={styles.pipeline}>{pipeline.map(({ title, caption, icon: Icon }, index) => <li key={title}><div className={`${styles.node} ${index === 0 || index === 7 ? styles.bookend : ""}`}><Icon size={21} /><div><strong>{title}</strong><span>{caption}</span></div>{index === 1 && <span className={styles.live}>Built</span>}</div>{index < pipeline.length - 1 && <ArrowDown size={20} className={styles.arrow} aria-hidden="true" />}</li>)}</ol><div className={styles.sideServices}><h3>Specialist services</h3><p>Connected through typed service boundaries</p>{[{ icon: Video, title: "Video service", caption: "Private room infrastructure" }, { icon: MessageSquare, title: "Chat / WebSocket service", caption: "Room-scoped conversations" }, { icon: Bell, title: "Notification service", caption: "Email · SMS · Push" }, { icon: CreditCard, title: "Payment gateway", caption: "Verified payment events" }].map(({ icon: Icon, title, caption }) => <div className={styles.node} key={title}><Icon size={20} /><div><strong>{title}</strong><span>{caption}</span></div></div>)}<div className={styles.cloudServices}>CloudFront · S3 · ECS / Lambda<br />RDS · CloudWatch</div></div></div><p className={styles.diagramNote}>A simplified conceptual request path, not a required linear dependency chain. Provider choices remain open.</p></div></div></section>
    <section className="container home-section"><div className="section-heading"><div><h2>Every layer has a purpose.</h2><p>Select a layer to see what exists now, and what comes next.</p></div></div><div className={styles.stackGrid}>{layers.map(layer => <button type="button" key={layer.id} aria-pressed={selected.id === layer.id} className={`${styles.stackCard} ${selected.id === layer.id ? styles.selected : ""}`} onClick={() => setSelected(layer)}><layer.icon size={23} strokeWidth={1.4} /><strong>{layer.title}</strong><span>{layer.technology}</span><ArrowUpRight size={14} className={styles.cardArrow} /></button>)}</div><div className={styles.detail} role="region" aria-label={`${selected.title} details`} aria-live="polite"><span>{selected.status}</span><h3>{selected.title}</h3><p>{selected.detail}</p></div></section>
    <section className={styles.readiness}><div className="container"><ShieldCheck size={32} strokeWidth={1.2} /><h2>Trust is a responsibility,<br />not a badge.</h2><p>A production launch needs more than a beautiful interface. Server-enforced access, encrypted transport, transactional reservations, payment-webhook verification, personal-data consent and retention, monitoring and recovery are essential next steps.</p><Link className="text-link" href="/astrologers">Experience the prototype <ArrowRight size={17} /></Link></div></section>
  </div>;
}
